/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as rootBackupImport } from './routes/__root.backup'
import { Route as IndexImport } from './routes/index'
import { Route as IndexBackup3Import } from './routes/index.backup3'
import { Route as IndexBackupImport } from './routes/index.backup'

// Create/Update Routes

const rootBackupRoute = rootBackupImport.update({
  id: '/__root/backup',
  path: '/backup',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const IndexBackup3Route = IndexBackup3Import.update({
  id: '/index/backup3',
  path: '/index/backup3',
  getParentRoute: () => rootRoute,
} as any)

const IndexBackupRoute = IndexBackupImport.update({
  id: '/index/backup',
  path: '/index/backup',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/__root/backup': {
      id: '/__root/backup'
      path: '/backup'
      fullPath: '/backup'
      preLoaderRoute: typeof rootBackupImport
      parentRoute: typeof rootRoute
    }
    '/index/backup': {
      id: '/index/backup'
      path: '/index/backup'
      fullPath: '/index/backup'
      preLoaderRoute: typeof IndexBackupImport
      parentRoute: typeof rootRoute
    }
    '/index/backup3': {
      id: '/index/backup3'
      path: '/index/backup3'
      fullPath: '/index/backup3'
      preLoaderRoute: typeof IndexBackup3Import
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/backup': typeof rootBackupRoute
  '/index/backup': typeof IndexBackupRoute
  '/index/backup3': typeof IndexBackup3Route
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/backup': typeof rootBackupRoute
  '/index/backup': typeof IndexBackupRoute
  '/index/backup3': typeof IndexBackup3Route
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/__root/backup': typeof rootBackupRoute
  '/index/backup': typeof IndexBackupRoute
  '/index/backup3': typeof IndexBackup3Route
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/backup' | '/index/backup' | '/index/backup3'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/backup' | '/index/backup' | '/index/backup3'
  id: '__root__' | '/' | '/__root/backup' | '/index/backup' | '/index/backup3'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  rootBackupRoute: typeof rootBackupRoute
  IndexBackupRoute: typeof IndexBackupRoute
  IndexBackup3Route: typeof IndexBackup3Route
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  rootBackupRoute: rootBackupRoute,
  IndexBackupRoute: IndexBackupRoute,
  IndexBackup3Route: IndexBackup3Route,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/__root/backup",
        "/index/backup",
        "/index/backup3"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/__root/backup": {
      "filePath": "__root.backup.tsx"
    },
    "/index/backup": {
      "filePath": "index.backup.tsx"
    },
    "/index/backup3": {
      "filePath": "index.backup3.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
