/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as April2026Import } from './routes/april2026'
import { Route as IndexImport } from './routes/index'

// Create/Update Routes

const April2026Route = April2026Import.update({
  id: '/april2026',
  path: '/april2026',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/april2026': {
      id: '/april2026'
      path: '/april2026'
      fullPath: '/april2026'
      preLoaderRoute: typeof April2026Import
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/april2026': typeof April2026Route
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/april2026': typeof April2026Route
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/april2026': typeof April2026Route
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/april2026'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/april2026'
  id: '__root__' | '/' | '/april2026'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  April2026Route: typeof April2026Route
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  April2026Route: April2026Route,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/april2026"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/april2026": {
      "filePath": "april2026.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
